apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django.fullname" . }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ required "secretKey is a required value." .Values.secretKey | b64enc | quote }}
{{- if .Values.databaseURL }}
  DATABASE_URL: {{ .Values.databaseURL | b64enc | quote }}
{{- end }}
{{- if .Values.redisURL }}
  REDIS_URL: {{ .Values.redisURL | b64enc | quote }}
{{- end }}
{{- if .Values.asteriskURL }}
  ASTERISK_URL: {{ .Values.asteriskURL | b64enc | quote }}
{{- end }}
{{- if .Values.odooURL }}
  ODOO_URL: {{ .Values.odooURL | b64enc | quote }}
{{- end }}
{{- if .Values.emailURL }}
  EMAIL_URL: {{ .Values.emailURL | b64enc | quote }}
{{- end }}
{{- if .Values.stripeLiveSecretKey }}
  STRIPE_LIVE_SECRET_KEY: {{ .Values.stripeLiveSecretKey | b64enc | quote }}
{{- end }}
{{- if .Values.djstripeWebhookSecret }}
  DJSTRIPE_WEBHOOK_SECRET: {{ .Values.djstripeWebhookSecret | b64enc | quote }}
{{- end }}
  google-credentials.json: {{ .Values.googleCredentials | b64enc | quote }}
