apiVersion: v2
name: django
description: DJANGO Backend to support the mobile applications, payments and user base.
type: application
version: 0.1.1
appVersion: 3.0


dependencies:
  - name: postgresql
    version: 10.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 12.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
