apiVersion: v2
name: django
description: DJANGO Backend to support the mobile applications, payments and user base.
type: application
version: 0.1.5
appVersion: 3.1

dependencies:
  - name: postgresql
    version: 11.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 16.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
